{
 "title": "12.0 observability demo",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   { "name": "nodeName", "label": "nodeName", "query": { "query": "label_values(nodeName)" } },
   { "name": "folderName", "label": "folderName", "query": { "query": "label_values(folderName)" } },
   { "name": "serviceType", "label": "serviceType", "query": { "query": "label_values(serviceType)" } },
   { "name": "serviceName", "label": "serviceName", "query": { "query": "label_values(serviceName)" } },
   { "name": "operation", "label": "operation", "query": { "query": "label_values(operation)" } },
   { "name": "username", "label": "username", "query": { "query": "label_values(username)" } },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Uptime and Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "up{job=~\"$job\"}*100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Service Error (%) ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 11, "y": 1 },
     "targets": [
      {
       "expr": " sum by (job, serviceName, serviceType, operation, username) (rate(requests_failed_total{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\"}[5m]))/ sum by (job, serviceName, serviceType, operation, username) (rate(requests_total{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\"}[5m]))*100>0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg Response Time by Service (sec)  - top 20",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 78 },
     "targets": [
      {
       "expr": "topk(20, sum by (job, serviceName, serviceType) (rate(requests_response_time_seconds_sum{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\", operation=~\"^.+$\"}[5m]))  / sum by (job, serviceName, serviceType) (rate ( requests_response_time_seconds_count{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg Response Time by User (sec) - top 20",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 78 },
     "targets": [
      {
       "expr": "topk(20, sum by (job, username) (rate(requests_response_time_seconds_sum{job=~\"$job\",username=~\"$username\", operation=~\"^.+$\"}[5m]))  / sum by (job, username) (rate ( requests_response_time_seconds_count{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg Response Time by Service, User, Operation (sec)  - top 20",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 78 },
     "targets": [
      {
       "expr": "topk(20, sum by (job,serviceName, serviceType, username, operation) (rate(requests_response_time_seconds_sum{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m]))  / sum by (job, serviceName, serviceType, username, operation) (rate ( requests_response_time_seconds_count{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests <0.5 sec by Service Type (%) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 156 },
     "targets": [
      {
       "expr": "topk(50, sum by (job, serviceType) (rate(requests_response_time_seconds_bucket{le=\"0.5\", job=~\"$job\",serviceType=~\"$serviceType\", operation=~\"^.+$\"}[5m]))  / sum by (job,serviceType) (rate ( requests_response_time_seconds_count{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))*100>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests <5 sec by Service Type (%) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 156 },
     "targets": [
      {
       "expr": "topk(50, sum by (job, serviceType) (rate(requests_response_time_seconds_bucket{le=\"5.0\", job=~\"$job\",serviceType=~\"$serviceType\", operation=~\"^.+$\"}[5m]))  / sum by (job,serviceType) (rate ( requests_response_time_seconds_count{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))*100>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests <10 sec by Service Type (%) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 156 },
     "targets": [
      {
       "expr": "topk(50, sum by (job, serviceType) (rate(requests_response_time_seconds_bucket{le=\"10.0\", job=~\"$job\",serviceType=~\"$serviceType\"}[5m]))  / sum by (job,serviceType) (rate ( requests_response_time_seconds_count{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))*100>0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top service (req/sec) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 79 },
     "targets": [
      {
       "expr": " topk(50,sum by (job, serviceName, serviceType) (rate( requests_response_time_seconds_count{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0 ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top user (req/sec) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 79 },
     "targets": [
      {
       "expr": "topk(50,sum by (job, username) (rate(requests_response_time_seconds_count{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top service, user, operation (req/sec) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 79 },
     "targets": [
      {
       "expr": "topk(50,sum by (job,serviceName, username, operation) (rate(requests_response_time_seconds_count{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Time Used by Service (sec/sec) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 157 },
     "targets": [
      {
       "expr": " topk(50,sum by (job, serviceName, serviceType) (rate( requests_response_time_seconds_sum{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0 ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Time Used by User (sec/sec) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 157 },
     "targets": [
      {
       "expr": "topk(50,sum by (job, username) (rate(requests_response_time_seconds_sum{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Time Used by Service, User, Operation (sec/sec) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 157 },
     "targets": [
      {
       "expr": "topk(50,sum by (job,serviceName, username, operation) (rate(requests_response_time_seconds_sum{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Requests in last 24 hrs by Service (req) ",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 167 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " topk(10,sum by (job, serviceName, serviceType) (increase( requests_response_time_seconds_sum{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[1d])))>0 ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Requests in last 24 hrs by User (req) ",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 167 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " topk(10,sum by (job, username) (increase( requests_response_time_seconds_sum{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[1d])))>0 ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Requests in last 24 hrs by Service, User, Operation (req) ",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 167 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": " topk(10,sum by (job, serviceType, serviceName, username, operation) (increase( requests_response_time_seconds_sum{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",username=~\"$username\", operation=~\"$operation\",operation=~\"^.+$\"}[1d])))>0 ",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Infrastructure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Used (%)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "cpu_percent{job=~\"$job\",nodeName=~\"$nodeName\"} * on (nodeName) group_left (osName, osBuild, osVersion) os_information>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Used (%)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 4 },
     "targets": [
      {
       "expr": "(memory_physical_total_GB-memory_available_GB{job=~\"$job\",nodeName=~\"$nodeName\"})/memory_physical_total_GB{job=~\"$job\",nodeName=~\"$nodeName\"}*100 * on (nodeName) group_left (osName, osBuild, osVersion) os_information>20",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Storage Used per Node(%)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 4 },
     "targets": [
      {
       "expr": "((sum by (job, nodeName, componentName) (disk_capacity_GB{job=~\"$job\",nodeName=~\"$nodeName\"})) - (sum by (job, nodeName, componentName) (disk_free_GB{job=~\"$job\",nodeName=~\"$nodeName\"}))) / (sum by (job, nodeName, componentName) (disk_capacity_GB{job=~\"$job\",nodeName=~\"$nodeName\"}))*100 * on (nodeName) group_left (osName, osBuild, osVersion) os_information>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Process CPU Cores Used (cores)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "processes_cpu_percent{job=~\"$job\",nodeName=~\"$nodeName\"}/100 * on (nodeName) group_left () cpu_logical_processor{job=~\"$job\",nodeName=~\"$nodeName\"} * on (nodeName) group_left (osName, osBuild, osVersion) os_information\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Process Memory (MB)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 14 },
     "targets": [
      {
       "expr": "processes_memory_MB{job=~\"$job\",nodeName=~\"$nodeName\"} * on (nodeName) group_left (osName, osBuild, osVersion) os_information\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Storage Used per Mount (%)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 14 },
     "targets": [
      {
       "expr": "((sum by (job, nodeName, componentName, diskMount) (disk_capacity_GB{job=~\"$job\",nodeName=~\"$nodeName\"})) - (sum by (job, nodeName, componentName, diskMount) (disk_free_GB{job=~\"$job\",nodeName=~\"$nodeName\"}))) / (sum by (job, nodeName, componentName, diskMount) (disk_capacity_GB{job=~\"$job\",nodeName=~\"$nodeName\"}))*100 * on (nodeName) group_left (osName, osBuild, osVersion) os_information>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Processes running (total)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "processes_running{job=~\"$job\",nodeName=~\"$nodeName\"} * on (nodeName) group_left (osName, osBuild, osVersion) os_information",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "System threads (total)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 24 },
     "targets": [
      {
       "expr": "system_threads{job=~\"$job\",nodeName=~\"$nodeName\"} * on (nodeName) group_left (osName, osBuild, osVersion) os_information",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Writes per node (KB/sec)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 24 },
     "targets": [
      {
       "expr": "sum by (job, nodeName, componentName) (rate(disk_write_bytes_total{job=~\"$job\",nodeName=~\"$nodeName\"}[5m]))/1024 * on (nodeName) group_left (osName, osBuild, osVersion) os_information>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Boot time (days)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "system_boot_time_seconds{job=~\"$job\",nodeName=~\"$nodeName\"}/3600/24 * on (nodeName) group_left (osName, osBuild, osVersion) os_information",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Queue Length per Node (total)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 34 },
     "targets": [
      {
       "expr": "disk_queue_length{job=~\"$job\",nodeName=~\"$nodeName\"} * on (nodeName) group_left (osName, osBuild, osVersion) os_information",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Reads per Node (KB/sec)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 34 },
     "targets": [
      {
       "expr": "sum by (job, nodeName, componentName) (rate(disk_read_bytes_total{job=~\"$job\",nodeName=~\"$nodeName\"}[5m]))/1024 * on (nodeName) group_left (osName, osBuild, osVersion) os_information",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "About", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Infrastructure ",
   "type": "table",
   "gridPos": { "h": 14, "w": 23, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "os_information {job=~\"$job\",nodeName=~\"$nodeName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpu_logical_processor{job=~\"$job\",nodeName=~\"$nodeName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpu_core_frequency_GHz{job=~\"$job\",nodeName=~\"$nodeName\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "memory_physical_total_GB{job=~\"$job\",nodeName=~\"$nodeName\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}