{
 "title": "ArcGIS Enterprise 12.1 on Windows/Linux/Kubernetes: Usage Analytics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   { "name": "serviceType", "label": "serviceType", "query": { "query": "label_values(serviceType)" } },
   { "name": "serviceName", "label": "serviceName", "query": { "query": "label_values(serviceName)" } },
   { "name": "operation", "label": "operation", "query": { "query": "label_values(operation)" } },
   { "name": "username", "label": "username", "query": { "query": "label_values(username)" } },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Users",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Portal User Logins Total (logins/hr)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase (users_login_total[1h])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Users (users/hr) ",
     "type": "timeseries",
     "description": "Collected from Server metrics",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 1 },
     "targets": [
      {
       "expr": "count by (job)(sum by (job, username)(increase(requests_total{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\", operation=~\"^.+$\"}[1h])) > 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Service Requests (req/hr)  by User,App ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 14, "y": 1 },
     "targets": [
      {
       "expr": "topk(10,sum by (job, username, appType) (increase(requests_response_time_seconds_counter_total{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[1h])))>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "User Load (req/hr) ",
     "type": "timeseries",
     "description": "Collected from Server metrics",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "topk(10,sum by (job, username) (increase(requests_response_time_seconds_counter_total{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[1h])))>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "User Busy Time per Hour  (%) ",
     "type": "timeseries",
     "description": "Collected from Server metrics",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 31 },
     "targets": [
      {
       "expr": "count_over_time(\r\n  (\r\n    sum by (job, username)(\r\n      rate(requests_total{operation!=\"\"}[5m])\r\n    ) > 0\r\n  )[1h:5m]\r\n) * 5/60*100\r\n",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Items and Services",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Items Count Total (count)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by (nodeName) (items_count) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Item Views Per Second (views/hr)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(items_viewed_total[1h])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests (req/hr) by Service Type",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "topk(10,sum by (job,serviceType) (increase(requests_response_time_seconds_counter_total{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[1h])))>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests (req/hr) by App, Service Type",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 32 },
     "targets": [
      {
       "expr": "topk(10,sum by (job,appType, serviceType) (increase(requests_response_time_seconds_counter_total{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[1h])))>0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}