{
 "title": "ArcGIS Enterprise 12.1 on Kubernetes: System Diagnostics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ArcGIS_datasource", "label": "ArcGIS datasource", "query": "prometheus" },
   { "name": "K8_datasource", "label": "K8 datasource", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   { "name": "nodeName", "label": "nodeName", "query": { "query": "label_values(nodeName)" } },
   { "name": "serviceType", "label": "serviceType", "query": { "query": "label_values(serviceType)" } },
   { "name": "serviceName", "label": "serviceName", "query": { "query": "label_values(serviceName)" } },
   { "name": "operation", "label": "operation", "query": { "query": "label_values(operation)" } },
   { "name": "username", "label": "username", "query": { "query": "label_values(username)" } },
   { "name": "pod", "label": "pod", "query": { "query": "label_values(pod)" } },
   { "name": "folderName", "label": "folderName", "query": { "query": "label_values(folderName)" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime and Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime (%)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "up{}*100 or relational_store_is_healthy*100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Service Error (%) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 1 },
     "targets": [
      {
       "expr": " sum by (job, serviceName, serviceType, operation, username) (rate(requests_failed_total{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\"}[5m]))/ sum by (job, serviceName, serviceType, operation, username) (rate(requests_total{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\"}[5m]))*100>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ArcGIS Services with Non‑Ready Pods",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 1 },
     "targets": [
      {
       "expr": "sum by (job, label_arcgis_gis_service_name) (\r\n  (\r\n    kube_pod_status_ready{\r\n      pod=~\"$pod\",\r\n      condition=\"true\"\r\n    } == bool 0\r\n  )\r\n  * on (pod, namespace)\r\n    group_left(label_arcgis_gis_service_name)\r\n    kube_pod_labels{\r\n      namespace=\"arcgis\",\r\n      label_arcgis_gis_service_name!=\"\"\r\n    }\r\n)>0\r\n",
       "legendFormat": "{{label_arcgis_gis_service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance: Service Response Time (s)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg Response Time by Service (s)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "topk(\r\n  10,\r\n  (\r\n    sum by (job, serviceName, serviceType) (\r\n      rate(\r\n        requests_response_time_seconds_sum{\r\n          job=~\"$job\",\r\n          folderName=~\"$folderName\",\r\n          serviceType=~\"$serviceType\",\r\n          serviceName=~\"$serviceName\",\r\n          operation=~\"^.+$\"\r\n        }[5m]\r\n      )\r\n    )\r\n    /\r\n    sum by (job, serviceName, serviceType) (\r\n      rate(\r\n        requests_total{\r\n          job=~\"$job\",\r\n          folderName=~\"$folderName\",\r\n          serviceType=~\"$serviceType\",\r\n          serviceName=~\"$serviceName\",\r\n          operation=~\"$operation\",\r\n          operation=~\"^.+$\"\r\n        }[5m]\r\n      )\r\n    )\r\n  )\r\n)\r\nand\r\nsum by (job, serviceName, serviceType) (\r\n  rate(\r\n    requests_total{\r\n      job=~\"$job\",\r\n      folderName=~\"$folderName\",\r\n      serviceType=~\"$serviceType\",\r\n      serviceName=~\"$serviceName\",\r\n      operation=~\"$operation\",\r\n      operation=~\"^.+$\"\r\n    }[5m]\r\n  )\r\n) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg Response Time by User (s)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 2 },
     "targets": [
      {
       "expr": "topk(\r\n  10,\r\n  (\r\n    sum by (job, username) (\r\n      rate(\r\n        requests_response_time_seconds_counter_total{\r\n          job=~\"$job\",\r\n          folderName=~\"$folderName\",\r\n          username=~\"$username\",\r\n          operation=~\"^.+$\"\r\n        }[5m]\r\n      )\r\n    )\r\n    /\r\n    sum by (job, username) (\r\n      rate(\r\n        requests_total{\r\n          job=~\"$job\",\r\n          folderName=~\"$folderName\",\r\n          serviceType=~\"$serviceType\",\r\n          serviceName=~\"$serviceName\",\r\n          username=~\"$username\",\r\n          operation=~\"$operation\",\r\n          operation=~\"^.+$\"\r\n        }[5m]\r\n      )\r\n    )\r\n  )\r\n)\r\nand\r\nsum by (job, username) (\r\n  rate(\r\n    requests_total{\r\n      job=~\"$job\",\r\n      folderName=~\"$folderName\",\r\n      serviceType=~\"$serviceType\",\r\n      serviceName=~\"$serviceName\",\r\n      username=~\"$username\",\r\n      operation=~\"$operation\",\r\n      operation=~\"^.+$\"\r\n    }[5m]\r\n  )\r\n) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg Response Time by Service, User, Operation (s) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 2 },
     "targets": [
      {
       "expr": "topk(\r\n  10,\r\n  (\r\n    sum by (job, serviceName, serviceType, username, operation) (\r\n      rate(\r\n        requests_response_time_seconds_counter_total{\r\n          job=~\"$job\",\r\n          folderName=~\"$folderName\",\r\n          serviceType=~\"$serviceType\",\r\n          serviceName=~\"$serviceName\",\r\n          operation=~\"$operation\",\r\n          username=~\"$username\",\r\n          operation=~\"^.+$\"\r\n        }[5m]\r\n      )\r\n    )\r\n    /\r\n    sum by (job, serviceName, serviceType, username, operation) (\r\n      rate(\r\n        requests_total{\r\n          job=~\"$job\",\r\n          folderName=~\"$folderName\",\r\n          serviceType=~\"$serviceType\",\r\n          serviceName=~\"$serviceName\",\r\n          operation=~\"$operation\",\r\n          username=~\"$username\",\r\n          operation=~\"^.+$\"\r\n        }[5m]\r\n      )\r\n    )\r\n  )\r\n)\r\nand\r\nsum by (job, serviceName, serviceType, username, operation) (\r\n  rate(\r\n    requests_total{\r\n      job=~\"$job\",\r\n      folderName=~\"$folderName\",\r\n      serviceType=~\"$serviceType\",\r\n      serviceName=~\"$serviceName\",\r\n      operation=~\"$operation\",\r\n      username=~\"$username\",\r\n      operation=~\"^.+$\"\r\n    }[5m]\r\n  )\r\n) > 0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance: Service Wait Time (s)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg Wait Time by Service (s)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "topk(10, sum by (job,serviceName) (rate(requests_wait_time_seconds_sum{folderName=~\"$folderName\",serviceName=~\"$serviceName\"}[5m]))  / sum by (job, serviceName) (rate ( requests_wait_time_seconds_count{folderName=~\"$folderName\",serviceName=~\"$serviceName\"}[5m])))>0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance: Service Histogram (%)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests <0.5 sec by Service Type (%) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 420 },
     "targets": [
      {
       "expr": "topk(10, sum by (job, serviceType) (rate(requests_response_time_seconds_bucket{le=\"0.5\", job=~\"$job\",folderName=~\"$folderName\",serviceType=~\"$serviceType\", operation=~\"^.+$\"}[5m]))  / sum by (job,serviceType) (rate ( requests_response_time_seconds_count{job=~\"$job\",folderName=~\"$folderName\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\", operation=~\"^.+$\"}[5m])))*100>0\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests <1 sec by Service Type (%) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 8, "y": 420 },
     "targets": [
      {
       "expr": "topk(50, sum by (job, serviceType) (rate(requests_response_time_seconds_bucket{le=\"1.0\", job=~\"$job\",serviceType=~\"$serviceType\", operation=~\"^.+$\"}[5m]))  / sum by (job,serviceType) (rate ( requests_response_time_seconds_count{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",operation=~\"^.+$\"}[5m])))*100>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests <10 sec by Service Type (%) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 15, "y": 420 },
     "targets": [
      {
       "expr": "topk(50, sum by (job, serviceType) (rate(requests_response_time_seconds_bucket{le=\"10.0\", job=~\"$job\",folderName=~\"$folderName\",serviceType=~\"$serviceType\"}[5m]))  / sum by (job,serviceType) (rate ( requests_response_time_seconds_count{job=~\"$job\",folderName=~\"$folderName\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",operation=~\"^.+$\"}[5m])))*100>0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "User Load: Service Requests Per Second",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service (req/s) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 421 },
     "targets": [
      {
       "expr": " topk(50,sum by (job, serviceName, serviceType) (rate( requests_response_time_seconds_count{job=~\"$job\",folderName=~\"$folderName\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\", operation=~\"^.+$\"}[5m])))>0 ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "User (req/s) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 421 },
     "targets": [
      {
       "expr": "topk(10,sum by (job, username) (rate(requests_response_time_seconds_counter_total{job=~\"$job\",folderName=~\"$folderName\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "AppType, Service, User, Operation (req/s) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 421 },
     "targets": [
      {
       "expr": "topk(10,sum by (job,appType, serviceName, username, operation) (rate(requests_response_time_seconds_counter_total{job=~\"$job\",folderName=~\"$folderName\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "User Load: Service Processing Time (seconds)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Time Used by Service (s/s) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 402 },
     "targets": [
      {
       "expr": " topk(10,sum by (job, serviceName, serviceType) (rate( requests_response_time_seconds_sum{job=~\"$job\",folderName=~\"$folderName\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",operation=~\"^.+$\"}[5m])))>0 ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Time Used by User (s/s) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 402 },
     "targets": [
      {
       "expr": "topk(50,sum by (job, username) (rate(requests_response_time_seconds_counter_total{job=~\"$job\",folderName=~\"$folderName\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Time Used by Service, User, Operation (s/s) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 402 },
     "targets": [
      {
       "expr": "topk(50,sum by (job,serviceName, username, operation) (rate(requests_response_time_seconds_counter_total{job=~\"$job\",folderName=~\"$folderName\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "System Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Used  (cores) by Service, Pod, Node",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum by (job, pod, namespace, node, label_arcgis_gis_service_name) (\r\n  (\r\n    rate(\r\n      container_cpu_usage_seconds_total{\r\n        container=\"main-container\",\r\n        pod=~\"$pod\",\r\n        node=~\"$nodeName\"\r\n      }[1m]\r\n    )\r\n  )\r\n  * on (pod, namespace)\r\n    group_left(label_arcgis_gis_service_name)\r\n    kube_pod_labels{\r\n      namespace=\"arcgis\",\r\n      label_arcgis_gis_service_name!=\"\"\r\n    }\r\n)\r\n> 0\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Used  (B) by Service, Pod, Node",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "sum by (pod, namespace, node, label_arcgis_gis_service_name) (\r\n  container_memory_working_set_bytes{\r\n    namespace=\"arcgis\",\r\n    container=\"main-container\"\r\n  }\r\n  * on (pod, namespace)\r\n    group_left(label_arcgis_gis_service_name)\r\n    kube_pod_labels{\r\n      namespace=\"arcgis\",\r\n      label_arcgis_gis_service_name!=\"\"\r\n    }\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Used  (cores) by Service",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 135 },
     "targets": [
      {
       "expr": "  sum by (label_arcgis_gis_service_name) (\r\n  rate(container_cpu_usage_seconds_total{\r\n    namespace=\"arcgis\",\r\n    container=\"main-container\",\r\n    cpu=\"total\"\r\n  }[1m])\r\n  *\r\n  on(pod)\r\n  group_left(label_arcgis_gis_service_name)\r\n  kube_pod_labels{\r\n    namespace=\"arcgis\",\r\n    label_arcgis_gis_service_name!=\"\"\r\n  }\r\n)\r\n> 0\r\n",
       "legendFormat": "{{label_arcgis_gis_service_name}}"
      }
     ]
    },
    {
     "title": "Memory (B) by Service",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 135 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "sum by (label_arcgis_gis_service_name) (\r\n  container_memory_working_set_bytes{\r\n    namespace=\"arcgis\",\r\n    container=\"main-container\"\r\n  }\r\n  * on (pod, namespace)\r\n    group_left(label_arcgis_gis_service_name)\r\n    kube_pod_labels{\r\n      namespace=\"arcgis\",\r\n      label_arcgis_gis_service_name!=\"\"\r\n    }\r\n)",
       "legendFormat": "{{label_arcgis_gis_service_name}}"
      }
     ]
    },
    {
     "title": "Running Pods  (count) By Service",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 145 },
     "targets": [
      {
       "expr": "sum by (label_arcgis_gis_service_name) ( kube_pod_status_phase{namespace=\"arcgis\",phase=\"Running\"}   * on(namespace, pod) group_left(label_arcgis_gis_service_name)   kube_pod_labels{ namespace=\"arcgis\",label_arcgis_gis_service_name!=\"\"} )>0",
       "legendFormat": "{{label_arcgis_gis_service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Infrastructure Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Used (%) by Node",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": " 100 - (\r\n  avg by (job,instance) (\r\n    rate(node_cpu_seconds_total{mode=\"idle\"}[1m])\r\n  )\r\n  * on(instance)\r\n    group_left(nodename)\r\n    max by (instance, nodename) (node_uname_info)\r\n  * 100\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Used (%) by Node",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 8 },
     "targets": [
      {
       "expr": "100 * (\r\n  1 - (\r\n    node_memory_MemAvailable_bytes\r\n    / node_memory_MemTotal_bytes\r\n    * on (instance)\r\n      group_left(nodename)\r\n      max by (instance, nodename) (node_uname_info)\r\n  )\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Used (%) by Node",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 8 },
     "targets": [
      {
       "expr": "100 *\r\n(\r\n  1 -\r\n  (\r\n    avg by (job,instance) (\r\n      node_filesystem_free_bytes{\r\n        fstype!~\"tmpfs|overlay|squashfs\",\r\n        mountpoint!~\"/var/lib/docker|/var/lib/kubelet\"\r\n      }\r\n    )\r\n    /\r\n    avg by (job,instance) (\r\n      node_filesystem_size_bytes{\r\n        fstype!~\"tmpfs|overlay|squashfs\",\r\n        mountpoint!~\"/var/lib/docker|/var/lib/kubelet\"\r\n      }\r\n    )\r\n  )\r\n)\r\n* on (instance)\r\n  group_left (nodename)\r\n  max by (job,instance, nodename) (node_uname_info)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Used (cores) by Node",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 106 },
     "targets": [
      {
       "expr": "sum by (job, instance, nodename) (\r\n  rate(node_cpu_seconds_total{mode!=\"idle\"}[1m])\r\n  * on (instance)\r\n    group_left (nodename)\r\n    max by (job, instance, nodename) (node_uname_info)\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Used (GB) by Node",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 106 },
     "targets": [
      {
       "expr": "(\r\n  node_memory_MemTotal_bytes\r\n  - node_memory_MemAvailable_bytes\r\n)\r\n/\r\n1024 / 1024 / 1024\r\n* on (instance)\r\n  group_left (nodename)\r\n  max by (instance, nodename) (node_uname_info)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Used (GB) by Node",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 106 },
     "targets": [
      {
       "expr": "sum by (job,instance, nodename) (\r\n  node_filesystem_size_bytes{\r\n    fstype!~\"tmpfs|overlay|squashfs\"\r\n  }\r\n  -\r\n  node_filesystem_free_bytes{\r\n    fstype!~\"tmpfs|overlay|squashfs\"\r\n  }\r\n)\r\n/\r\n1024 / 1024 / 1024\r\n* on (instance)\r\n  group_left (nodename)\r\n  max by (job,instance, nodename) (node_uname_info)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Throttling Rate by ArcGIS Service and Pod",
     "type": "timeseries",
     "description": "High value means the container is frequently throttled.\nThis indicates CPU starvation, which can degrade performance.\nConsider: Increase CPU limits, Optimize workload, Use autoscaling.",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 116 },
     "targets": [
      {
       "expr": "sum by (job, pod, label_arcgis_gis_service_name) (\r\n  rate(\r\n    container_cpu_cfs_throttled_periods_total{\r\n      container!=\"\",\r\n    }[1m]\r\n  )\r\n  * on (pod, namespace)\r\n    group_left (label_arcgis_gis_service_name)\r\n    kube_pod_labels{\r\n      namespace=\"arcgis\",\r\n      label_arcgis_gis_service_name!=\"\"\r\n    }\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Network (Mbps) by Service, Pod, Node",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 116 },
     "targets": [
      {
       "expr": "sum by (job, pod, namespace, node, label_arcgis_gis_service_name) (\r\n  (\r\n    rate(\r\n      container_network_transmit_bytes_total{\r\n        node=~\"$nodeName\",\r\n        pod=~\"$pod\"\r\n      }[1m]\r\n    )\r\n    / 1024 / 1024\r\n  )\r\n  * on (pod, namespace)\r\n    group_left(label_arcgis_gis_service_name)\r\n    kube_pod_labels{\r\n      namespace=\"arcgis\",\r\n      label_arcgis_gis_service_name!=\"\"\r\n    }\r\n)\r\n> 0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU Available (%) by Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(\r\n  avg by (job,instance) (\r\n    rate(node_cpu_seconds_total{node=~\"$nodeName\", mode=\"idle\"}[1m])\r\n  )\r\n  * on(instance)\r\n    group_left(nodename)\r\n    max by (job, instance, nodename) (node_uname_info)\r\n  * 100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Available (%) by Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 9 },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  node_memory_MemAvailable_bytes{node=~\"$nodeName\"}\r\n  / node_memory_MemTotal_bytes {node=~\"$nodeName\"}\r\n)\r\n* on (instance)\r\n  group_left (nodename)\r\n  max by (instance, nodename) (node_uname_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Available (%) by Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "100 *\r\n(\r\n  avg by (job,instance) (\r\n    node_filesystem_free_bytes{\r\n      fstype!~\"tmpfs|overlay|squashfs\",\r\n      mountpoint!~\"/var/lib/docker|/var/lib/kubelet\"\r\n    }\r\n  )\r\n  /\r\n  avg by (job, instance) (\r\n    node_filesystem_size_bytes{\r\n      fstype!~\"tmpfs|overlay|squashfs\",\r\n      mountpoint!~\"/var/lib/docker|/var/lib/kubelet\"\r\n    }\r\n  )\r\n)\r\n* on (instance)\r\n  group_left (nodename)\r\n  max by (job, instance, nodename) (node_uname_info)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage as % of Container CPU Limit (ArcGIS Services)",
   "type": "timeseries",
   "description": "High value means the container is frequently throttled.\nThis indicates CPU starvation, which can degrade performance.\nConsider: Increase CPU limits, Optimize workload, Use autoscaling.",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "100 *\r\nmax by (job, pod, node, container, label_arcgis_gis_service_name) (\r\n  rate(\r\n    container_cpu_usage_seconds_total{\r\n      container=\"main-container\",\r\n      namespace=\"arcgis\",\r\n      node=~\"$nodeName\",\r\n    }[1m]\r\n  )\r\n  /\r\n  on (pod, namespace, node, container)\r\n    kube_pod_container_resource_limits{\r\n      resource=\"cpu\",\r\n      namespace=\"arcgis\",\r\n    }\r\n  * on (pod, namespace)\r\n    group_left(label_arcgis_gis_service_name)\r\n    kube_pod_labels{\r\n      label_arcgis_gis_service_name!=\"\"\r\n    }\r\n)\r\n> 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OOMKilled by Pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 19 },
   "targets": [
    {
     "expr": "sum by (job, pod, label_arcgis_gis_service_name) (\r\n  (\r\n    max_over_time(\r\n      kube_pod_container_status_last_terminated_reason{\r\n        namespace=\"arcgis\",\r\n        reason=\"OOMKilled\"\r\n      }[5m:]\r\n    )\r\n    > 0\r\n  )\r\n  * on (pod)\r\n    group_left(label_arcgis_gis_service_name)\r\n    kube_pod_labels{\r\n      namespace=\"arcgis\",\r\n      label_arcgis_gis_service_name!=\"\"\r\n    }\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Available (%) by Node",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 19 },
   "targets": [
    {
     "expr": "sum by (job, pod, label_arcgis_gis_service_name) (\r\n  (\r\n    kube_pod_status_ready{\r\n      condition=\"true\",\r\n      pod=~\"$pod\"\r\n    } > 0\r\n  )\r\n  * on (pod, namespace)\r\n    group_left(label_arcgis_gis_service_name)\r\n    kube_pod_labels{\r\n      namespace=\"arcgis\",\r\n      label_arcgis_gis_service_name!=\"\"\r\n    }\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage as % of Container Memory Limit (ArcGIS Services)",
   "type": "timeseries",
   "description": "High value means the container is frequently throttled.\nThis indicates CPU starvation, which can degrade performance.\nConsider: Increase CPU limits, Optimize workload, Use autoscaling.",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 29 },
   "targets": [
    {
     "expr": "100 *\r\nmax by (pod, namespace, node, container, label_arcgis_gis_service_name) (\r\n  rate(\r\n    container_memory_usage_bytes{\r\n      image!=\"\",\r\n      container=\"main-container\",\r\n      namespace=\"arcgis\",\r\n      node=~\"$nodeName\"\r\n    }[5m]\r\n  )\r\n  /\r\n  on (pod, namespace, node, container)\r\n    kube_pod_container_resource_limits{\r\n      resource=\"memory\",\r\n      container=\"main-container\",\r\n      namespace=\"arcgis\",\r\n      node=~\"$nodeName\"\r\n    }\r\n  * on (pod, namespace)\r\n    group_left(label_arcgis_gis_service_name)\r\n    kube_pod_labels{\r\n      namespace=\"arcgis\",\r\n      label_arcgis_gis_service_name!=\"\"\r\n    }\r\n)\r\n> 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container CPU/Memory Usage and Configuration",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (pod, namespace, node, label_arcgis_gis_service_name) (\r\n  sum(\r\n    kube_pod_container_resource_requests{\r\n      namespace=\"arcgis\",\r\n      node=~\"$nodeName\",\r\n      pod=~\"$pod\",\r\n      resource=\"cpu\"\r\n    }\r\n  ) by (pod, namespace, node)\r\n  * on (pod, namespace)\r\n    group_left(label_arcgis_gis_service_name)\r\n    kube_pod_labels{\r\n      namespace=\"arcgis\",\r\n      label_arcgis_gis_service_name!=\"\"\r\n    }\r\n)\r\n"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"arcgis\",node=~\"$nodeName\",pod=~\"$pod\",resource=\"cpu\",}) by (pod, namespace, node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"arcgis\",node=~\"$nodeName\",pod=~\"$pod\", resource=\"memory\"}) by (pod, namespace, node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"arcgis\",node=~\"$nodeName\",pod=~\"$pod\", resource=\"memory\"}) by (pod, namespace, node)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"arcgis\",container=\"main-container\",node=~\"$nodeName\",pod=~\"$pod\"}[5m])) by (pod, namespace, node)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\", container!=\"\",namespace=\"arcgis\",node=~\"$nodeName\",pod=~\"$pod\"}) by (pod, namespace, node)"
    }
   ]
  }
 ]
}