{
 "title": "ArcGIS 12.0 on K8  template",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   { "name": "nodeName", "label": "nodeName", "query": { "query": "label_values(nodeName)" } },
   { "name": "folderName", "label": "folderName", "query": { "query": "label_values(folderName)" } },
   { "name": "serviceType", "label": "serviceType", "query": { "query": "label_values(serviceType)" } },
   { "name": "serviceName", "label": "serviceName", "query": { "query": "label_values(serviceName)" } },
   { "name": "operation", "label": "operation", "query": { "query": "label_values(operation)" } },
   { "name": "username", "label": "username", "query": { "query": "label_values(username)" } },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Uptime and Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "up{job=~\"$job\"}*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Error (%) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": " sum by (job, serviceName, serviceType, operation, username) (rate(requests_failed_total{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\"}[5m]))/ sum by (job, serviceName, serviceType, operation, username) (rate(requests_total{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\"}[5m]))*100>0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Avg Response Time by Service (sec)  - top 20",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "topk(20, sum by (job, serviceName, serviceType) (rate(requests_response_time_seconds_sum{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\", operation=~\"^.+$\"}[5m]))  / sum by (job, serviceName, serviceType) (rate ( requests_response_time_seconds_count{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Response Time by User (sec) - top 20",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 10 },
   "targets": [
    {
     "expr": "topk(20, sum by (job, username) (rate(requests_response_time_seconds_sum{job=~\"$job\",username=~\"$username\", operation=~\"^.+$\"}[5m]))  / sum by (job, username) (rate ( requests_response_time_seconds_count{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Response Time by Service, User, Operation (sec)  - top 20",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 10 },
   "targets": [
    {
     "expr": "topk(20, sum by (job,serviceName, serviceType, username, operation) (rate(requests_response_time_seconds_sum{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m]))  / sum by (job, serviceName, serviceType, username, operation) (rate ( requests_response_time_seconds_count{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests <0.05 sec by Service Type (%) ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "topk(50, sum by (job, serviceType) (rate(requests_response_time_seconds_bucket{le=\"0.05\", job=~\"$job\",serviceType=~\"$serviceType\", operation=~\"^.+$\"}[5m]))  / sum by (job,serviceType) (rate ( requests_response_time_seconds_count{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))*100>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests <5 sec by Service Type (%) ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 20 },
   "targets": [
    {
     "expr": "topk(50, sum by (job, serviceType) (rate(requests_response_time_seconds_bucket{le=\"5.0\", job=~\"$job\",serviceType=~\"$serviceType\", operation=~\"^.+$\"}[5m]))  / sum by (job,serviceType) (rate ( requests_response_time_seconds_count{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))*100>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests <1 sec by Service Type (%) ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 20 },
   "targets": [
    {
     "expr": "topk(50, sum by (job, serviceType) (rate(requests_response_time_seconds_bucket{le=\"1.0\", job=~\"$job\",serviceType=~\"$serviceType\"}[5m]))  / sum by (job,serviceType) (rate ( requests_response_time_seconds_count{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))*100>0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Total Time Used by Service (sec/sec) ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": " topk(50,sum by (job, serviceName, serviceType) (rate( requests_response_time_seconds_sum{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Time Used by User (sec/sec) ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 31 },
   "targets": [
    {
     "expr": "topk(50,sum by (job, username) (rate(requests_response_time_seconds_sum{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Time Used by Service, User, Operation (sec/sec) ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 31 },
   "targets": [
    {
     "expr": "topk(50,sum by (job,serviceName, username, operation) (rate(requests_response_time_seconds_sum{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top service (req/sec) ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": " topk(50,sum by (job, serviceName, serviceType) (rate( requests_response_time_seconds_count{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top user (req/sec) ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 41 },
   "targets": [
    {
     "expr": "topk(50,sum by (job, username) (rate(requests_response_time_seconds_count{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top service, user, operation (req/sec) ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 41 },
   "targets": [
    {
     "expr": "topk(50,sum by (job,serviceName, username, operation) (rate(requests_response_time_seconds_count{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests in last 24 hrs by Service (req) ",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " topk(10,sum by (job, serviceName, serviceType) (increase( requests_response_time_seconds_sum{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[1d])))>0 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests in last 24 hrs by User (req) ",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " topk(10,sum by (job, username) (increase( requests_response_time_seconds_sum{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[1d])))>0 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Requests in last 24 hrs by Service, User, Operation (req) ",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 14, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " topk(10,sum by (job, serviceType, serviceName, username, operation) (increase( requests_response_time_seconds_sum{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",username=~\"$username\", operation=~\"$operation\",operation=~\"^.+$\"}[1d])))>0 ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}