{
 "title": "ArcGIS Enterprise 12.1 on Windows/Linux: System Diagnostics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   { "name": "nodeName", "label": "nodeName", "query": { "query": "label_values(nodeName)" } },
   { "name": "folderName", "label": "folderName", "query": { "query": "label_values(folderName)" } },
   { "name": "serviceType", "label": "serviceType", "query": { "query": "label_values(serviceType)" } },
   { "name": "serviceName", "label": "serviceName", "query": { "query": "label_values(serviceName)" } },
   { "name": "operation", "label": "operation", "query": { "query": "label_values(operation)" } },
   { "name": "username", "label": "username", "query": { "query": "label_values(username)" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime and Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime (%)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "up{job=~\"$job\"}*100 or relational_store_is_healthy*100",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Service Error (%) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 10, "y": 1 },
     "targets": [
      {
       "expr": " sum by (job, serviceName, serviceType, operation, username) (rate(requests_failed_total{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\"}[5m]))/ sum by (job, serviceName, serviceType, operation, username) (rate(requests_total{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\"}[5m]))*100>0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance: Service Response Time (s)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg Response Time by Service (s)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "topk(\r\n  10,\r\n  (\r\n    sum by (job, serviceName, serviceType) (\r\n      rate(\r\n        requests_response_time_seconds_sum{\r\n          job=~\"$job\",\r\n          folderName=~\"$folderName\",\r\n          serviceType=~\"$serviceType\",\r\n          serviceName=~\"$serviceName\",\r\n          operation=~\"^.+$\"\r\n        }[5m]\r\n      )\r\n    )\r\n    /\r\n    sum by (job, serviceName, serviceType) (\r\n      rate(\r\n        requests_total{\r\n          job=~\"$job\",\r\n          folderName=~\"$folderName\",\r\n          serviceType=~\"$serviceType\",\r\n          serviceName=~\"$serviceName\",\r\n          operation=~\"$operation\",\r\n          operation=~\"^.+$\"\r\n        }[5m]\r\n      )\r\n    )\r\n  )\r\n)\r\nand\r\nsum by (job, serviceName, serviceType) (\r\n  rate(\r\n    requests_total{\r\n      job=~\"$job\",\r\n      folderName=~\"$folderName\",\r\n      serviceType=~\"$serviceType\",\r\n      serviceName=~\"$serviceName\",\r\n      operation=~\"$operation\",\r\n      operation=~\"^.+$\"\r\n    }[5m]\r\n  )\r\n) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg Response Time by User (s)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 2 },
     "targets": [
      {
       "expr": "topk(\r\n  10,\r\n  (\r\n    sum by (job, username) (\r\n      rate(\r\n        requests_response_time_seconds_counter_total{\r\n          job=~\"$job\",\r\n          folderName=~\"$folderName\",\r\n          username=~\"$username\",\r\n          operation=~\"^.+$\"\r\n        }[5m]\r\n      )\r\n    )\r\n    /\r\n    sum by (job, username) (\r\n      rate(\r\n        requests_total{\r\n          job=~\"$job\",\r\n          folderName=~\"$folderName\",\r\n          serviceType=~\"$serviceType\",\r\n          serviceName=~\"$serviceName\",\r\n          username=~\"$username\",\r\n          operation=~\"$operation\",\r\n          operation=~\"^.+$\"\r\n        }[5m]\r\n      )\r\n    )\r\n  )\r\n)\r\nand\r\nsum by (job, username) (\r\n  rate(\r\n    requests_total{\r\n      job=~\"$job\",\r\n      folderName=~\"$folderName\",\r\n      serviceType=~\"$serviceType\",\r\n      serviceName=~\"$serviceName\",\r\n      username=~\"$username\",\r\n      operation=~\"$operation\",\r\n      operation=~\"^.+$\"\r\n    }[5m]\r\n  )\r\n) > 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg Response Time by Service, User, Operation (s) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 2 },
     "targets": [
      {
       "expr": "topk(\r\n  10,\r\n  (\r\n    sum by (job, serviceName, serviceType, username, operation) (\r\n      rate(\r\n        requests_response_time_seconds_counter_total{\r\n          job=~\"$job\",\r\n          folderName=~\"$folderName\",\r\n          serviceType=~\"$serviceType\",\r\n          serviceName=~\"$serviceName\",\r\n          operation=~\"$operation\",\r\n          username=~\"$username\",\r\n          operation=~\"^.+$\"\r\n        }[5m]\r\n      )\r\n    )\r\n    /\r\n    sum by (job, serviceName, serviceType, username, operation) (\r\n      rate(\r\n        requests_total{\r\n          job=~\"$job\",\r\n          folderName=~\"$folderName\",\r\n          serviceType=~\"$serviceType\",\r\n          serviceName=~\"$serviceName\",\r\n          operation=~\"$operation\",\r\n          username=~\"$username\",\r\n          operation=~\"^.+$\"\r\n        }[5m]\r\n      )\r\n    )\r\n  )\r\n)\r\nand\r\nsum by (job, serviceName, serviceType, username, operation) (\r\n  rate(\r\n    requests_total{\r\n      job=~\"$job\",\r\n      folderName=~\"$folderName\",\r\n      serviceType=~\"$serviceType\",\r\n      serviceName=~\"$serviceName\",\r\n      operation=~\"$operation\",\r\n      username=~\"$username\",\r\n      operation=~\"^.+$\"\r\n    }[5m]\r\n  )\r\n) > 0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Performance: Service Histogram (%)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests <0.5 sec by Service Type (%) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 163 },
     "targets": [
      {
       "expr": "topk(10, sum by (job, serviceType) (rate(requests_response_time_seconds_bucket{le=\"0.5\", job=~\"$job\",folderName=~\"$folderName\",serviceType=~\"$serviceType\", operation=~\"^.+$\"}[5m]))  / sum by (job,serviceType) (rate ( requests_response_time_seconds_count{job=~\"$job\",folderName=~\"$folderName\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\", operation=~\"^.+$\"}[5m])))*100>0\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests <1 sec by Service Type (%) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 8, "y": 163 },
     "targets": [
      {
       "expr": "topk(50, sum by (job, serviceType) (rate(requests_response_time_seconds_bucket{le=\"1.0\", job=~\"$job\",serviceType=~\"$serviceType\", operation=~\"^.+$\"}[5m]))  / sum by (job,serviceType) (rate ( requests_response_time_seconds_count{job=~\"$job\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",operation=~\"^.+$\"}[5m])))*100>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Requests <10 sec by Service Type (%) ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 15, "y": 163 },
     "targets": [
      {
       "expr": "topk(50, sum by (job, serviceType) (rate(requests_response_time_seconds_bucket{le=\"10.0\", job=~\"$job\",folderName=~\"$folderName\",serviceType=~\"$serviceType\"}[5m]))  / sum by (job,serviceType) (rate ( requests_response_time_seconds_count{job=~\"$job\",folderName=~\"$folderName\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",operation=~\"^.+$\"}[5m])))*100>0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "User Load: Service Requests Per Second",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Per Second (req/s) by Service",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 164 },
     "targets": [
      {
       "expr": " topk(50,sum by (job, serviceName, serviceType) (rate( requests_response_time_seconds_count{job=~\"$job\",folderName=~\"$folderName\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\", operation=~\"^.+$\"}[5m])))>0 ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Per Second (req/s) by User",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 164 },
     "targets": [
      {
       "expr": "topk(10,sum by (job, username) (rate(requests_response_time_seconds_counter_total{job=~\"$job\",folderName=~\"$folderName\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": " Requests Per Second (req/s) by AppType, Service, User, Operation",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 164 },
     "targets": [
      {
       "expr": "topk(10,sum by (job,appType, serviceName, username, operation) (rate(requests_response_time_seconds_counter_total{job=~\"$job\",folderName=~\"$folderName\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "User Load: Service Processing Time (seconds)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Time Used (sec/sec) by Service ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 165 },
     "targets": [
      {
       "expr": " topk(10,sum by (job, serviceName, serviceType) (rate( requests_response_time_seconds_sum{job=~\"$job\",folderName=~\"$folderName\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",operation=~\"^.+$\"}[5m])))>0 ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Time Used (sec/sec) by User ",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 165 },
     "targets": [
      {
       "expr": "topk(50,sum by (job, username) (rate(requests_response_time_seconds_counter_total{job=~\"$job\",folderName=~\"$folderName\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Time Used  (sec/sec) by Service, User, Operation",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 165 },
     "targets": [
      {
       "expr": "topk(50,sum by (job,serviceName, username, operation) (rate(requests_response_time_seconds_counter_total{job=~\"$job\",folderName=~\"$folderName\",serviceType=~\"$serviceType\",serviceName=~\"$serviceName\",operation=~\"$operation\",username=~\"$username\", operation=~\"^.+$\"}[5m])))>0",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "System Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process CPU (%)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 166 },
     "targets": [
      {
       "expr": "processes_cpu_percent{job=~\"$job\",nodeName=~\"$nodeName\"} * on (instance) group_left (componentName,cpuLogicalProcessor,osName, osBuild, osVersion) about_information>0\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Process Memory (B)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "processes_memory_MB{job=~\"$job\",nodeName=~\"$nodeName\"} * 1024*1024 * on (instance) group_left (componentName,cpuLogicalProcessor,osName, osBuild, osVersion) about_information>0\r\n",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Processes running (total)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 166 },
     "targets": [
      {
       "expr": "processes_running{job=~\"$job\",nodeName=~\"$nodeName\"} * on (instance) group_left (osName, osBuild, osVersion) about_information",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Infrastructure Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Used (%)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 177 },
     "targets": [
      {
       "expr": "cpu_percent{job=~\"$job\",nodeName=~\"$nodeName\"} * on (instance) group_left (componentName,cpuLogicalProcessor,osName, osBuild, osVersion) about_information>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Writes per node (KB/sec)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 177 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "sum by (job, nodeName, componentName) (rate(disk_write_bytes_total{job=~\"$job\",nodeName=~\"$nodeName\"}[5m]))/1024 ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Queue Length per Node (total)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 187 },
     "targets": [
      {
       "expr": "disk_queue_length{job=~\"$job\",nodeName=~\"$nodeName\"} * on (instance) group_left (osName, osBuild, osVersion) about_information",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Reads per node (B/sec)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 187 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "sum by (job, nodeName, componentName) (rate(disk_read_bytes_total{job=~\"$job\",nodeName=~\"$nodeName\"}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Available (%)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 442 },
     "targets": [
      {
       "expr": "100-cpu_percent{job=~\"$job\",nodeName=~\"$nodeName\"} * on (instance) group_left (componentName,cpuLogicalProcessor,osName, osBuild, osVersion) about_information>0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Available (GB)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 442 },
     "targets": [
      {
       "expr": "\r\nmemory_available_GB * on(instance)    group_left(memoryPhysicalTotalGB)   about_information",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "System threads (total)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 14, "y": 442 },
     "fieldConfig": { "defaults": { "unit": "sishort" } },
     "targets": [
      {
       "expr": "system_threads{job=~\"$job\",nodeName=~\"$nodeName\"} * on (instance) group_left (osName, osBuild, osVersion) about_information",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Storage Used per Node(%)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 452 },
     "targets": [
      {
       "expr": "((sum by (job, nodeName, componentName) (disk_capacity_GB{job=~\"$job\",nodeName=~\"$nodeName\"})) - (sum by (job, nodeName, componentName) (disk_free_GB{job=~\"$job\",nodeName=~\"$nodeName\"}))) / (sum by (job, nodeName, componentName) (disk_capacity_GB{job=~\"$job\",nodeName=~\"$nodeName\"}))*100 ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Disk Storage Used per Mount (%)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 452 },
     "targets": [
      {
       "expr": "((sum by (job, nodeName, componentName,diskMount, diskName) (disk_capacity_GB{job=~\"$job\",nodeName=~\"$nodeName\"})) - (sum by (job, nodeName, componentName, diskMount, diskName) (disk_free_GB{job=~\"$job\",nodeName=~\"$nodeName\"}))) / (sum by (job, nodeName, componentName,diskMount, diskName) (disk_capacity_GB{job=~\"$job\",nodeName=~\"$nodeName\"}))*100 ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ArcGIS Relational Data Store Table Size (MB)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 462 },
     "targets": [
      {
       "expr": "relational_table_size{job=~\"$job\"} * on (instance) group_left (nodeName, componentName) about_information",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "ArcGIS Relational Data Store Table Row Count(count)",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 7, "y": 462 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "relational_store_row_count{job=~\"$job\"} * on (instance) group_left (nodeName, componentName) about_information",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Infrastructure ",
     "type": "table",
     "gridPos": { "h": 14, "w": 23, "x": 0, "y": 472 },
     "targets": [
      {
       "expr": "about_information {job=~\"$job\",nodeName=~\"$nodeName\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}